export const RUN_SAMPLE = 'RUN_SAMPLE';
export const STOP_SAMPLE = 'STOP_SAMPLE';
export const APPEND_CONSOLE_LOG = 'APPEND_CONSOLE_LOG';

export const SELECT_PROJECT = 'SELECT_PROJECT';
export const SET_EDITOR_PATH = 'SET_EDITOR_PATH';
export const SET_PROJECT_CONFIG = 'SET_PROJECT_CONFIG';
export const SHOW_RUNNING_INFO = 'SHOW_RUNNING_INFO';

export const SWITCH_HELP = 'SWITCH_HELP';
export const SET_COMPONENT_SIZE = 'SET_COMPONENT_SIZE';

export const SWITCH_ON_OFF_BOARD = 'SWITCH_ON_OFF_BOARD';
export const SET_SENSOR_DATA = 'SET_SENSOR_DATA';
